"use client";
import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    name: "English",
    flag: "🇬🇧",
    // ── Sidebar ──
    dashboard: "Dashboard",
    analyzeMessage: "Analyze Message",
    imageAnalysis: "Image Analysis",
    threatHistory: "Threat History",
    reports: "Reports",
    settings: "Settings",
    library: "Library",
    help: "Help & Support",
    logOut: "Log out",
    logIn: "Log in",
    signUp: "Sign up",
    // ── Library ──
    libraryTitle: "Negarit Library",
    librarySub: "Educational resources about cybersecurity, phishing, and how Negarit AI protects you.",
    actionableTips: "Actionable Tips",
    videoTitle: "Watch & Learn",
    videoSub: "Curated cybersecurity videos to deepen your understanding.",
    downloadGuide: "Download Full Guide (.DOCX)",
    // ── Common ──
    loading: "Loading...",
    error: "Error",
    back: "Back",
    home: "Home",
    // ── Dashboard ──
    welcomeBack: "Welcome back,",
    securityCommandCenter: "Your AI-powered security command center",
    totalAnalyses: "Total Analyses",
    threatsDetected: "Threats Detected",
    safe: "Safe",
    suspicious: "Suspicious",
    quickActions: "Quick Actions",
    detectPhishing: "Detect phishing in emails, SMS, and chats",
    checkUrl: "Check URL",
    scanLinks: "Scan links for malware and phishing",
    detectDeepfakes: "Detect AI-generated deepfakes",
    recentActivity: "Recent Activity",
    noAnalysesYet: "No analyses yet.",
    runFirstScan: "Run your first scan",
    scoreLabel: "Score:",
    // ── Analyze Message ──
    senderEmailOptional: "Sender Email (optional)",
    senderEmailPlaceholder: "sender@example.com",
    domainOptional: "Domain (optional)",
    domainPlaceholder: "example.com",
    senderPhoneOptional: "Sender Phone (optional)",
    senderPhonePlaceholder: "+251-XXX-XXXXXX",
    messagePlaceholder: "Paste suspicious message here...",
    analyzingButton: "Analyzing...",
    analyzeContent: "Analyze Content",
    uploadScreenshot: "Upload Screenshot",
    aiAnalyzingMessage: "AI model analyzing message...",
    analysisComplete: "Analysis Complete",
    lowRisk: "Low Risk",
    highRisk: "High Risk",
    detectedFlags: "Detected Flags",
    senderAnalysisTitle: "Sender Analysis",
    senderVerdict: "Sender Verdict",
    emailReputation: "Email Reputation",
    domainReputation: "Domain Reputation",
    phoneReputation: "Phone Reputation",
    copyReport: "Copy Report",
    // ── Analyze Image ──
    imageDeepfakeAnalysis: "Image & Deepfake Analysis",
    dropImageHere: "Drop image here or click to upload",
    maxSizeFormats: "Max size: 50MB | Formats: PNG, JPEG, WEBP",
    uploadImage: "Upload Image",
    analyzeImageBtn: "Analyze Image",
    remove: "Remove",
    analyzingImage: "Analyzing image for deepfake artifacts...",
    analysisResultsId: "Analysis Results — ID: IMG-",
    sourceImage: "Source Image",
    deepfakeProbability: "Deepfake Probability",
    lowLikelihood: "Low likelihood",
    possibleAiGeneration: "Possible AI generation",
    highLikelihood: "High likelihood of AI generation",
    logoDetection: "Logo Detection",
    noAiLogosDetected: "No AI generation logos detected",
    confidenceScore: "Confidence",
    imageAuthenticity: "Image Authenticity",
    failedVerification: "Failed multi-layer verification",
    partialVerification: "Partial verification",
    passedVerification: "Passed verification",
    forgeryDetection: "Forgery Detection",
    forgeryThreat: "THREAT — Metadata tampering detected. Original EXIF data stripped or modified.",
    forgeryClear: "CLEAR — No signs of metadata tampering or forgery.",
    aiRecommendation: "AI Recommendation",
    blockRecommendation: "BLOCK — Strong indicators of AI manipulation. Do not interact with embedded links.",
    allowRecommendation: "ALLOW — Image appears authentic. No immediate action required.",
    analysisDetails: "Analysis Details",
    downloadPdf: "Download PDF",
    // ── Threat History ──
    noThreatHistory: "No threat history yet.",
    runAnalysisToSee: "Run an analysis to see results here.",
    type: "Type",
    content: "Content",
    verdict: "Verdict",
    date: "Date",
    // ── Reports ──
    exportDetailedReports: "Export and view detailed security reports.",
    exportCsv: "Export CSV",
    exportJson: "Export JSON",
    noHistoryYet: "No analysis history yet.",
    runAnalysisReports: "Run an analysis to generate reports.",
    // ── Settings ──
    profile: "Profile",
    notSignedIn: "Not signed in",
    security: "Security",
    authMethod: "Authentication Method",
    emailAndPassword: "Email and password",
    active: "Active",
    sessionLabel: "Session",
    loggedInWithJwt: "Logged in with JWT token",
    signOut: "Sign Out",
    dataStorage: "Data & Storage",
    analysisHistory: "Analysis History",
    storedLocally: "Stored locally in your browser",
    clearHistory: "Clear History",
    appVersion: "App Version",
    negaritAiVersion: "Negarit AI v1.0.0",
    upToDate: "Up-to-date",
    about: "About",
    aboutDescription: "Negarit AI is an AI-powered fraud detection system that protects users from phishing attacks, fake messages, and AI-generated deepfakes across Email, SMS, WhatsApp, Telegram, and social media platforms.",
    copyright: "© Negarit AI. All rights reserved.",
    clearHistoryConfirm: "Clear all analysis history? This cannot be undone.",
    historyCleared: "Analysis history cleared.",
    // ── Help ──
    understandingCyberThreats: "Understanding Cyber Threats",
    phishing: "Phishing",
    phishingDesc: "Fake messages impersonating banks, government agencies, or companies to steal login credentials and personal data.",
    smishing: "Smishing",
    smishingDesc: "Phishing via SMS text messages. Scammers send fake alerts about package deliveries, bank issues, or account verification.",
    deepfakes: "Deepfakes",
    deepfakesDesc: "AI-generated images, audio, or video designed to impersonate real people. Used in scams, disinformation, and identity fraud.",
    urlSpoofing: "URL Spoofing",
    urlSpoofingDesc: "Malicious links that appear legitimate but redirect to fake websites designed to steal your information.",
    socialEngineering: "Social Engineering",
    socialEngineeringDesc: "Psychological manipulation tricking people into divulging confidential information or performing actions that compromise security.",
    vishing: "Vishing",
    vishingDesc: "Voice phishing conducted over phone calls. Scammers pose as bank representatives, tech support, or government officials.",
    securityAwarenessTips: "Security Awareness Tips",
    tip1Title: "Check the Sender",
    tip1Desc: "Always verify the sender's email address or phone number. Scammers often spoof legitimate addresses with small changes.",
    tip2Title: "Hover Before You Click",
    tip2Desc: "Hover your mouse over links before clicking to see the actual URL. If it doesn't match the claimed destination, don't click.",
    tip3Title: "Urgency Is a Red Flag",
    tip3Desc: "Messages claiming your account will be suspended, a payment is overdue, or you've won a prize are common phishing tactics.",
    tip4Title: "Don't Share Personal Info",
    tip4Desc: "Legitimate organizations will never ask for your password, PIN, or OTP via email or SMS.",
    tip5Title: "Verify Attachments",
    tip5Desc: "Unexpected attachments, especially .zip, .exe, or .docm files, can contain malware.",
    tip6Title: "Enable Two-Factor Authentication",
    tip6Desc: "2FA adds an extra layer of security even if your password is compromised.",
    tip7Title: "Use Unique Passwords",
    tip7Desc: "Never reuse passwords across services. Use a password manager to generate and store strong, unique passwords.",
    tip8Title: "Report Suspicious Messages",
    tip8Desc: "Forward phishing emails to your organization's security team or relevant authorities.",
    faqSection: "Frequently Asked Questions",
    faq1Q: "What is Negarit AI?",
    faq1A: "Negarit AI is an AI-powered fraud detection system that analyzes messages, sender info, URLs, and images for phishing, scams, and deepfakes.",
    faq2Q: "How does the risk score work?",
    faq2A: "The risk score ranges from 0 (safe) to 100 (dangerous). Scores below 30 are Low Risk, 30-60 are Suspicious, and above 60 are High Risk.",
    faq3Q: "What platforms does it support?",
    faq3A: "Negarit AI can analyze content from Email, SMS, WhatsApp, Telegram, and social media platforms.",
    faq4Q: "How accurate is the deepfake detection?",
    faq4A: "The AI model detects AI-generated and manipulated images by analyzing visual artifacts, metadata inconsistencies, and generation fingerprints.",
    faq5Q: "Is my data stored or shared?",
    faq5A: "Analysis results are stored locally in your browser. Message and image content is sent to the AI model for analysis only.",
    faq6Q: "How do I analyze a sender?",
    faq6A: "When analyzing a message, you can optionally enter the sender's email address, domain name, or phone number for sender reputation analysis.",
    needMoreHelp: "Need More Help?",
    contactDescription: "If you have additional questions or need support, reach out to our team.",
    contactSupport: "Contact Support",
    // ── Login ──
    negaritAi: "Negarit AI",
    commandCenter: "The Command Center for Digital Trust.",
    detectPhishingDeepfakes: "Detect phishing, deepfakes, and AI-generated scams before they compromise your security.",
    accuracy994: "99.4% Accuracy",
    zeroDayProtected: "Zero-day Protected",
    joinOver10k: "Join over 10,000+ security teams globally.",
    enterCredentials: "Enter your credentials to access your dashboard",
    emailAddress: "Email address",
    emailPlaceholder: "name@company.com",
    password: "Password",
    forgotPassword: "Forgot password?",
    signingIn: "Signing in...",
    signIn: "Sign in",
    orContinueWith: "Or continue with",
    googleAuthInfo: "Google sign-in requires a Client ID (see .env.local)",
    dontHaveAccount: "Don't have an account?",
    createAccount: "Create an account",
    protectedByNegarit: "Protected by Negarit AI",
    serverError: "Cannot reach server. Make sure the backend is running on port 5000.",
    // ── Register ──
    secureDigitalFuture: "Secure Your Digital Future.",
    createAccountDesc: "Create your account today and protect against phishing, deepfakes, and AI-generated scams with enterprise-grade security.",
    fillDetails: "Fill in your details to get started",
    fullName: "Full Name",
    namePlaceholder: "John Doe",
    confirmPassword: "Confirm Password",
    creatingAccount: "Creating account...",
    alreadyHaveAccount: "Already have an account?",
    passwordsDoNotMatch: "Passwords do not match",
    trustedBy10k: "Trusted by 10,000+ security teams globally.",
    // ── Analyze Page ──
    threatAnalysis: "Threat Analysis",
    submitContent: "Submit suspicious content for AI-powered detection",
    messageTab: "Message",
    messageTabDesc: "Paste suspicious emails, SMS, or chat messages",
    urlTab: "URL",
    urlTabDesc: "Scan links for malware, phishing, and redirects",
    imageTab: "Image",
    imageTabDesc: "Upload screenshots to detect deepfakes and AI manipulation",
    clickToUpload: "Click to upload image",
    pngJpgSupported: "PNG, JPG, WEBP supported",
    enterUrl: "Enter suspicious URL...",
    pasteMessageHere: "Paste the suspicious email, SMS, or chat message here...",
    clear: "Clear",
    results: "Results",
    submitToSeeResults: "Submit content to see analysis results",
    aiWillReturn: "The AI will return a risk score, verdict, and explanation",
    aiAnalyzing: "AI model analyzing...",
    checkingPatterns: "Checking for phishing patterns and anomalies",
    riskScore: "Risk Score",
    analysisInfo: "Analysis Info",
    // ── Not Found ──
    pageNotFound: "Page Not Found",
    pageNotFoundDesc: "The page you're looking for doesn't exist or has been moved. Let's get you back on track.",
    goBack: "Go Back",
    backToHome: "Back to Home",
    protectingDigitalTrust: "— Protecting your digital trust",
    // ── ChatBot ──
    aiAssistant: "Negarit AI Assistant",
    askAboutCybersecurity: "Ask about cybersecurity...",
    sorryCouldNotProcess: "Sorry, I couldn't process that.",
    networkErrorChat: "Network error. Please try again.",
    welcomeMessage: "Hi! I'm Negarit AI Assistant. Ask me about phishing, cybersecurity, or what Negarit AI can do for you.",
    // ── Navbar ──
    navAnalyze: "Analyze",
    navFeatures: "Features",
    navHowItWorks: "How it Works",
    navFaq: "FAQ",
    startFreeTrial: "Start Free Trial",
    toggleMenu: "Toggle menu",
    // ── HeroSection ──
    enterpriseGradeProtection: "Enterprise Grade Protection",
    heroHeading: "Protect Yourself From AI Scams, Phishing & Deepfakes",
    heroDescription: "Negarit AI analyzes suspicious messages, URLs, screenshots, and AI-generated images to detect cyber threats before they reach you.",
    analyzeNow: "Analyze Now",
    learnMore: "Learn More",
    trustedBy: "Trusted by",
    securityProfessionals: "security professionals",
    // ── Features ──
    everythingToStaySafe: "Everything You Need to Stay Safe",
    sixEnginesWorking: "Six powerful engines working together to protect your organization from modern cyber threats.",
    aiMessageAnalysisTitle: "AI Message Analysis",
    aiMessageAnalysisDesc: "Instantly analyze suspicious emails and SMS. Detect urgency markers, LLM-generated text patterns, and spear-phishing attempts.",
    imageDeepfakeDetectionTitle: "Image Deepfake Detection",
    imageDeepfakeDetectionDesc: "Examine pixel-level noise patterns, lighting inconsistencies, and blending artifacts to expose AI-generated faces and documents.",
    urlScannerTitle: "URL Scanner",
    urlScannerDesc: "Deep-scan links in isolated sandboxes. Follow redirects, analyze DOMs, and check against real-time threat intelligence.",
    platformSupportTitle: "Platform Support",
    platformSupportDesc: "Native integrations via API, browser extensions, and chat bots for WhatsApp, Telegram, and Slack.",
    realtimeAlertsTitle: "Real-time Alerts",
    realtimeAlertsDesc: "Get instantaneous notifications via webhooks or SMS when high-confidence threats target your organization.",
    enterpriseReportsTitle: "Enterprise Reports",
    enterpriseReportsDesc: "Export detailed PDF reports of threat analyses for security teams, compliance officers, or law enforcement.",
    // ── Workflow ──
    securityInThreeSteps: "Security in Three Simple Steps",
    workflowDesc: "From submission to verdict in seconds — no training required.",
    submitContentStep: "Submit Content",
    submitContentStepDesc: "Paste a URL, upload an image, or forward a suspicious message to our dashboard or API.",
    aiAnalysisStep: "AI Analysis",
    aiAnalysisStepDesc: "Our models dissect the content for linguistic anomalies, deepfake traces, and malicious code.",
    getResultsStep: "Get Results",
    getResultsStepDesc: "Receive an instant verdict (Safe, Suspicious, or Danger) with a detailed breakdown of findings.",
    // ── Testimonials ──
    testimonials: "Testimonials",
    trustedByTeams: "Trusted by Security Teams",
    testimonialsDesc: "Hear from the professionals who rely on Negarit AI every day.",
    testimonial1Text: "Negarit AI caught a highly sophisticated spear-phishing campaign that bypassed our standard email gateway. The deepfake voice analysis for executive impersonation is unparalleled.",
    testimonial1Author: "Sarah Drasner",
    testimonial1Role: "CISO, FinTech Global",
    testimonial2Text: "We deployed the WhatsApp bot for our high-net-worth clients. They can now forward suspicious crypto links and get an immediate safety rating. It's saved millions in potential fraud.",
    testimonial2Author: "Marcus Reed",
    testimonial2Role: "VP of Security, Vault Digital",
    testimonial3Text: "The API integration was seamless. We pipe all user-uploaded KYC documents through Negarit to detect AI-generated synthetic IDs. It's incredibly fast and accurate.",
    testimonial3Author: "Elena Lin",
    testimonial3Role: "Lead Engineer, Trust & Safety",
    // ── FAQ Section ──
    faqSectionTitle: "Frequently Asked Questions",
    faqSectionDesc: "Everything you need to know about Negarit AI.",
    faq1Q: "How accurate is the deepfake detection?",
    faq1A: "Negarit AI uses multi-modal analysis, examining pixel inconsistencies, metadata, and audio-visual sync to achieve 99.4% accuracy.",
    faq2Q: "Can I use it for my whole team?",
    faq2A: "Yes, Negarit AI supports team-wide deployments with role-based access and centralized reporting.",
    faq3Q: "Do you store the content I analyze?",
    faq3A: "No, analyzed content is processed securely and not stored unless explicitly requested.",
    faq4Q: "Does it work with WhatsApp and Telegram?",
    faq4A: "Yes, we provide native bots for WhatsApp and Telegram to protect users where they work.",
    faq5Q: "How fast is the URL scanner?",
    faq5A: "Our sandboxed scanner delivers results in under 2 seconds, even for complex redirect chains.",
    // ── Footer ──
    product: "Product",
    resources: "Resources",
    company: "Company",
    documentation: "Documentation",
    apiReference: "API Reference",
    securityReports: "Security Reports",
    blog: "Blog",
    aboutUs: "About Us",
    careers: "Careers",
    contact: "Contact",
    privacyPolicy: "Privacy Policy",
    allSystemsOperational: "All systems operational",
    copyrightFooter: "© 2024 Negarit AI Inc. All rights reserved.",
    footerDescription: "Enterprise-grade protection against AI scams, phishing, and deepfakes. Securing the digital frontier.",
  },
  am: {
    name: "አማርኛ",
    flag: "🇪🇹",
    // ── Sidebar ──
    dashboard: "ዳሽቦርድ",
    analyzeMessage: "መልእክት ተንትን",
    imageAnalysis: "ምስል ትንተና",
    threatHistory: "የስጋት ታሪክ",
    reports: "ሪፖርቶች",
    settings: "ቅንብሮች",
    library: "ቤተ መጻሕፍት",
    help: "እርዳታ እና ድጋፍ",
    logOut: "ውጣ",
    logIn: "ግባ",
    signUp: "ተመዝገብ",
    // ── Library ──
    libraryTitle: "የኔጋሪት ቤተ መጻሕፍት",
    librarySub: "ስለ ሳይበር ደህንነት፣ ማጭበርበር እና ኔጋሪት ኤአይ እንዴት እንደሚከላከል የትምህርት መረጃዎች።",
    actionableTips: "ተግባራዊ ምክሮች",
    videoTitle: "ተመልከት እና ተማር",
    videoSub: "የሳይበር ደህንነት ግንዛቤዎን ለማሳደግ የተመረጡ ቪዲዮዎች።",
    downloadGuide: "ሙሉ መመሪያ አውርድ (.DOCX)",
    // ── Common ──
    loading: "በመጫን ላይ...",
    error: "ስህተት",
    back: "ተመለስ",
    home: "ቤት",
    // ── Dashboard ──
    welcomeBack: "እንኳን ደህና መጡ፣",
    securityCommandCenter: "የእርስዎ AI የተጎላበተ የደህንነት ትዕዛዝ ማእከል",
    totalAnalyses: "ጠቅላላ ትንታኔዎች",
    threatsDetected: "የተገኙ ስጋቶች",
    safe: "አስተማማኝ",
    suspicious: "አጠራጣሪ",
    quickActions: "ፈጣን እርምጃዎች",
    detectPhishing: "በኢሜል፣ ኤስኤምኤስ እና ቻት ውስጥ ማጭበርበርን ያግኙ",
    checkUrl: "ዩአርኤል ያረጋግጡ",
    scanLinks: "ሊንኮችን ለማልዌር እና ለማጭበርበር ይቃኙ",
    detectDeepfakes: "በAI የተፈጠሩ ሐሰተኛ ምስሎችን ያግኙ",
    recentActivity: "የቅርብ ጊዜ እንቅስቃሴ",
    noAnalysesYet: "ገና ምንም ትንታኔ የለም።",
    runFirstScan: "የመጀመሪያ ቅኝትዎን ያሂዱ",
    scoreLabel: "ውጤት:",
    // ── Analyze Message ──
    senderEmailOptional: "የላኪ ኢሜይል (አማራጭ)",
    senderEmailPlaceholder: "ላኪ@ምሳሌ.com",
    domainOptional: "ጎራ (አማራጭ)",
    domainPlaceholder: "ምሳሌ.com",
    senderPhoneOptional: "የላኪ ስልክ (አማራጭ)",
    senderPhonePlaceholder: "+251-XXX-XXXXXX",
    messagePlaceholder: "አጠራጣሪ መልእክት እዚህ ይለጥፉ...",
    analyzingButton: "በመተንተን ላይ...",
    analyzeContent: "ይዘት ተንትን",
    uploadScreenshot: "ስክሪን ሾት ስቀል",
    aiAnalyzingMessage: "AI ሞዴል መልእክቱን እየተነተነ ነው...",
    analysisComplete: "ትንተና ተጠናቋል",
    lowRisk: "ዝቅተኛ ስጋት",
    highRisk: "ከፍተኛ ስጋት",
    detectedFlags: "የተገኙ ምልክቶች",
    senderAnalysisTitle: "የላኪ ትንተና",
    senderVerdict: "የላኪ ፍርድ",
    emailReputation: "የኢሜይል ዝና",
    domainReputation: "የጎራ ዝና",
    phoneReputation: "የስልክ ዝና",
    copyReport: "ሪፖርት ቅዳ",
    // ── Analyze Image ──
    imageDeepfakeAnalysis: "ምስል እና ዲፕፌክ ትንተና",
    dropImageHere: "ምስል እዚህ ይጣሉ ወይም ለመጫን ይጫኑ",
    maxSizeFormats: "ከፍተኛ መጠን: 50ሜባ | ቅርጸቶች: PNG, JPEG, WEBP",
    uploadImage: "ምስል ጫን",
    analyzeImageBtn: "ምስል ተንትን",
    remove: "አስወግድ",
    analyzingImage: "ምስሉ ለዲፕፌክ ቅርሶች እየተተነተነ ነው...",
    analysisResultsId: "የትንተና ውጤቶች — መለያ: IMG-",
    sourceImage: "የመጀመሪያ ምስል",
    deepfakeProbability: "የዲፕፌክ እድል",
    lowLikelihood: "ዝቅተኛ እድል",
    possibleAiGeneration: "AI መፈጠር ይቻላል",
    highLikelihood: "ከፍተኛ የAI መፈጠር እድል",
    logoDetection: "ሎጎ መፈለግ",
    noAiLogosDetected: "ምንም የAI ማመንጨት ሎጎዎች አልተገኙም",
    confidenceScore: "እምነት",
    imageAuthenticity: "የምስል ትክክለኛነት",
    failedVerification: "የተሳካለት ባለብዙ-ሽፋን ማረጋገጫ",
    partialVerification: "ከፊል ማረጋገጫ",
    passedVerification: "ማረጋገጫውን አልፏል",
    forgeryDetection: "የሐሰት መለየት",
    forgeryThreat: "ስጋት — የሜታዳታ ጣልቃ ገብነት ተገኝቷል።",
    forgeryClear: "ንጹህ — ምንም የሜታዳታ ጣልቃ ገብነት ወይም የሐሰት ምልክቶች የሉም።",
    aiRecommendation: "AI ምክር",
    allowRecommendation: "ፍቀድ — ምስሉ ትክክለኛ ይመስላል።",
    analysisDetails: "የትንተና ዝርዝሮች",
    downloadPdf: "ፒዲኤፍ አውርድ",
    // ── Threat History ──
    noThreatHistory: "ገና ምንም የስጋት ታሪክ የለም።",
    runAnalysisToSee: "ውጤቶችን ለማየት ትንታኔ ያሂዱ።",
    type: "አይነት",
    content: "ይዘት",
    verdict: "ፍርድ",
    date: "ቀን",
    // ── Reports ──
    exportDetailedReports: "ዝርዝር የደህንነት ሪፖርቶችን ያፍሱ እና ይመልከቱ።",
    exportCsv: "CSV አፍስስ",
    exportJson: "JSON አፍስስ",
    noHistoryYet: "ገና ምንም የትንተና ታሪክ የለም።",
    runAnalysisReports: "ሪፖርቶችን ለማመንጨት ትንታኔ ያሂዱ።",
    // ── Settings ──
    profile: "መገለጫ",
    notSignedIn: "አልገቡም",
    security: "ደህንነት",
    authMethod: "የማረጋገጫ ዘዴ",
    emailAndPassword: "ኢሜይል እና የይለፍ ቃል",
    active: "ንቁ",
    sessionLabel: "ክፍለ ጊዜ",
    loggedInWithJwt: "በJWT ቶከን ተገብቷል",
    signOut: "ውጣ",
    dataStorage: "ውሂብ እና ማከማቻ",
    analysisHistory: "የትንተና ታሪክ",
    storedLocally: "በአሳሽዎ ውስጥ በአካባቢው ተከማችቷል",
    clearHistory: "ታሪክ አጽዳ",
    appVersion: "የመተግበሪያ ስሪት",
    negaritAiVersion: "ኔጋሪት AI v1.0.0",
    upToDate: "ወቅታዊ",
    about: "ስለ",
    aboutDescription: "ኔጋሪት AI በAI የተጎላበተ የማጭበርበር መለያ ስርዓት ነው።",
    copyright: "© ኔጋሪት AI. መብቱ በህግ የተጠበቀ ነው።",
    clearHistoryConfirm: "ሁሉንም የትንተና ታሪክ ያጸዳሉ? ይህ መቀልበስ አይቻልም።",
    historyCleared: "የትንተና ታሪክ ተጸድቷል።",
    // ── Help ──
    understandingCyberThreats: "የሳይበር ስጋቶችን መረዳት",
    phishing: "ፊሽንግ",
    phishingDesc: "የባንኮችን፣ የመንግስት ኤጀንሲዎችን ወይም ኩባንያዎችን አስመስለው የመግቢያ ማረጋገጫዎችን ለመስረቅ የሚላኩ ሐሰተኛ መልእክቶች።",
    smishing: "ስሚሽንግ",
    smishingDesc: "በኤስኤምኤስ የሚደረግ ፊሽንግ። አጭበርባሪዎች ስለ እሽግ አቅርቦት፣ የባንክ ችግሮች ወይም የመለያ ማረጋገጫ ሐሰተኛ ማንቂያዎችን ይልካሉ።",
    deepfakes: "ዲፕፌኮች",
    deepfakesDesc: "እውነተኛ ሰዎችን ለመምሰል የተነደፉ በAI የተፈጠሩ ምስሎች፣ ድምጾች ወይም ቪዲዮዎች።",
    urlSpoofing: "ዩአርኤል ማስመሰል",
    urlSpoofingDesc: "ሕጋዊ የሚመስሉ ነገር ግን ወደ ሐሰተኛ ድረ-ገጾች የሚያዞሩ ተንኮል-አዘል ሊንኮች።",
    socialEngineering: "ማህበራዊ ምህንድስና",
    socialEngineeringDesc: "ሚስጥራዊ መረጃ እንዲሰጡ ሰዎችን በስነ-ልቦና መጠቀሚያ ማታለል።",
    vishing: "ቪሽንግ",
    vishingDesc: "በስልክ ጥሪ የሚደረግ የድምጽ ማጭበርበር። አጭበርባሪዎች የባንክ ተወካዮች፣ የቴክኒክ ድጋፍ ወይም የመንግስት ባለስልጣናት አድርገው ይቀርባሉ።",
    securityAwarenessTips: "የደህንነት ግንዛቤ ምክሮች",
    tip1Title: "ላኪውን ያረጋግጡ",
    tip1Desc: "ሁልጊዜ የላኪውን ኢሜይል ወይም ስልክ ቁጥር ያረጋግጡ።",
    tip2Title: "ከመጫንዎ በፊት ይንጠለጠሉ",
    tip2Desc: "ትክክለኛውን ዩአርኤል ለማየት ከመጫንዎ በፊት አይጤዎን በሊንኮች ላይ ያንጠልጥሉ።",
    tip3Title: "አስቸኳይ ሁኔታ ቀይ ባንዲራ ነው",
    tip3Desc: "መለያዎ እንደሚታገድ፣ ክፍያ እንደዘገየ ወይም ሽልማት እንዳሸነፉ የሚገልጹ መልእክቶች የተለመዱ የማጭበርበሪያ ዘዴዎች ናቸው።",
    tip4Title: "የግል መረጃ አያጋሩ",
    tip4Desc: "ሕጋዊ ድርጅቶች የይለፍ ቃልዎን፣ ፒንዎን ወይም ኦቲፒዎን በኢሜይል ወይም በኤስኤምኤስ በጭራሽ አይጠይቁም።",
    tip5Title: "አባሪዎችን ያረጋግጡ",
    tip5Desc: "ያልተጠበቁ አባሪዎች፣ በተለይ .zip፣ .exe ወይም .docm ፋይሎች፣ ማልዌር ሊይዙ ይችላሉ።",
    tip6Title: "ባለሁለት-ደረጃ ማረጋገጫን ያንቁ",
    tip6Desc: "2FA የይለፍ ቃልዎ ቢጋለጥም ተጨማሪ የደህንነት ሽፋን ይሰጣል።",
    tip7Title: "ልዩ የይለፍ ቃሎችን ይጠቀሙ",
    tip7Desc: "በአገልግሎቶች መካከል የይለፍ ቃሎችን በጭራሽ አይጠቀሙ።",
    tip8Title: "አጠራጣሪ መልእክቶችን ሪፖርት ያድርጉ",
    tip8Desc: "የማጭበርበር ኢሜይሎችን ለድርጅትዎ የደህንነት ቡድን ወይም ባለስልጣናት ያስተላልፉ።",
    faqSection: "በተደጋጋሚ የሚጠየቁ ጥያቄዎች",
    faq1Q: "ኔጋሪት AI ምንድን ነው?",
    faq1A: "ኔጋሪት AI መልእክቶችን፣ የላኪ መረጃን፣ ዩአርኤሎችን እና ምስሎችን ለማጭበርበር እና ለዲፕፌክ የሚመረምር በAI የተጎላበተ ስርዓት ነው።",
    faq2Q: "የአደጋ ውጤቱ እንዴት ይሰራል?",
    faq2A: "የአደጋ ውጤቱ ከ0 (አስተማማኝ) እስከ 100 (አደገኛ) ነው። ከ30 በታች ዝቅተኛ፣ 30-60 አጠራጣሪ፣ ከ60 በላይ ከፍተኛ ነው።",
    faq3Q: "ምን ዓይነት መድረኮችን ይደግፋል?",
    faq3A: "ኔጋሪት AI ከኢሜይል፣ ኤስኤምኤስ፣ ዋትሳፕ፣ ቴሌግራም እና ማህበራዊ ሚዲያ መድረኮች ይዘትን መተንተን ይችላል።",
    faq4Q: "የዲፕፌክ መለየቱ ምን ያህል ትክክለኛ ነው?",
    faq4A: "የAI ሞዴሉ የምስል ጥበባዊ ቅርሶችን፣ የሜታዳታ አለመመጣጠን እና የማመንጨት አሻራዎችን በመመርመር 99.4% ትክክለኛነትን ያስመዘግባል።",
    faq5Q: "ውሂቤ ይከማቻል ወይም ይጋራል?",
    faq5A: "የትንተና ውጤቶች በአሳሽዎ ውስጥ በአካባቢው ይከማቻሉ። የመልእክት እና የምስል ይዘት ለትንተና ብቻ ወደ AI ሞዴል ይላካል።",
    faq6Q: "ላኪን እንዴት መተንተን እችላለሁ?",
    faq6A: "መልእክትን በሚተነትኑበት ጊዜ የላኪውን ኢሜይል፣ የጎራ ስም ወይም ስልክ ቁጥር በአማራጭነት ማስገባት ይችላሉ።",
    needMoreHelp: "ተጨማሪ እርዳታ ያስፈልግዎታል?",
    contactDescription: "ተጨማሪ ጥያቄዎች ካሉዎት ወይም ድጋፍ ከፈለጉ ቡድናችንን ያነጋግሩ።",
    contactSupport: "ድጋፍ ያግኙ",
    // ── Login ──
    negaritAi: "ኔጋሪት AI",
    commandCenter: "የዲጂታል እምነት ትዕዛዝ ማእከል።",
    detectPhishingDeepfakes: "ደህንነትዎን ከማጭበርበር፣ ዲፕፌክ እና በAI ከሚፈጠሩ ማጭበርበሮች ይጠብቁ።",
    accuracy994: "99.4% ትክክለኛነት",
    zeroDayProtected: "ከዜሮ-ቀን የተጠበቀ",
    joinOver10k: "በአለም አቀፍ ደረጃ ከ10,000+ የደህንነት ቡድኖች ጋር ይቀላቀሉ።",
    enterCredentials: "ዳሽቦርድዎን ለመድረስ የምዝገባ መረጃዎን ያስገቡ",
    emailAddress: "ኢሜይል አድራሻ",
    emailPlaceholder: "ስም@ኩባንያ.com",
    password: "የይለፍ ቃል",
    forgotPassword: "የይለፍ ቃል ረሱ?",
    signingIn: "በመግባት ላይ...",
    signIn: "ግባ",
    orContinueWith: "ወይም በዚህ ይቀጥሉ",
    googleAuthInfo: "ጎግል መግቢያ የደንበኛ መለያ ያስፈልገዋል (.env.local ይመልከቱ)",
    dontHaveAccount: "መለያ የለዎትም?",
    createAccount: "መለያ ይፍጠሩ",
    protectedByNegarit: "በኔጋሪት AI የተጠበቀ",
    serverError: "አገልጋዩ ላይ መድረስ አልተቻለም። የኋላ አገልጋዩ በፖርት 5000 ላይ መስራቱን ያረጋግጡ።",
    // ── Register ──
    secureDigitalFuture: "ዲጂታል የወደፊትዎን ያስጠብቁ።",
    createAccountDesc: "ዛሬ መለያዎን ይፍጠሩ እና ከማጭበርበር፣ ዲፕፌክ እና በAI ከሚፈጠሩ ማጭበርበሮች ይጠበቁ።",
    fillDetails: "ለመጀመር ዝርዝሮችዎን ይሙሉ",
    fullName: "ሙሉ ስም",
    namePlaceholder: "ዮሐንስ ደሴ",
    confirmPassword: "የይለፍ ቃል ያረጋግጡ",
    creatingAccount: "መለያ በመፍጠር ላይ...",
    alreadyHaveAccount: "መለያ አለዎት?",
    passwordsDoNotMatch: "የይለፍ ቃላት አይዛመዱም",
    trustedBy10k: "በአለም አቀፍ ደረጃ ከ10,000+ የደህንነት ቡድኖች የታመነ።",
    // ── Analyze Page ──
    threatAnalysis: "የስጋት ትንተና",
    submitContent: "ለAI የተጎላበተ ምርመራ አጠራጣሪ ይዘት ያስገቡ",
    messageTab: "መልእክት",
    messageTabDesc: "አጠራጣሪ ኢሜይሎችን፣ ኤስኤምኤስ ወይም የቻት መልእክቶችን ይለጥፉ",
    urlTab: "ዩአርኤል",
    urlTabDesc: "ሊንኮችን ለማልዌር፣ ማጭበርበር እና ማዞሪያ ይቃኙ",
    imageTab: "ምስል",
    imageTabDesc: "ዲፕፌክ እና AI ጥቀርሻን ለመለየት ስክሪን ሾቶችን ይጫኑ",
    clickToUpload: "ምስል ለመጫን ይጫኑ",
    pngJpgSupported: "PNG, JPG, WEBP ይደገፋሉ",
    enterUrl: "አጠራጣሪ ዩአርኤል ያስገቡ...",
    pasteMessageHere: "አጠራጣሪ ኢሜይል፣ ኤስኤምኤስ ወይም የቻት መልእክት እዚህ ይለጥፉ...",
    clear: "አጽዳ",
    results: "ውጤቶች",
    submitToSeeResults: "የትንተና ውጤቶችን ለማየት ይዘት ያስገቡ",
    aiWillReturn: "AI የአደጋ ውጤት፣ ፍርድ እና ማብራሪያ ይመልሳል",
    aiAnalyzing: "AI ሞዴል እየተነተነ ነው...",
    checkingPatterns: "የማጭበርበር ንድፎችን እና ያልተለመዱ ነገሮችን በመፈተሽ ላይ",
    riskScore: "የአደጋ ውጤት",
    analysisInfo: "የትንተና መረጃ",
    // ── Not Found ──
    pageNotFound: "ገጽ አልተገኘም",
    pageNotFoundDesc: "የሚፈልጉት ገጽ የለም ወይም ተንቀሳቅሷል። ወደ ትክክለኛው መንገድ እንመልስዎታለን።",
    goBack: "ተመለስ",
    backToHome: "ወደ መነሻ ገጽ",
    protectingDigitalTrust: "— የዲጂታል እምነትዎን መጠበቅ",
    // ── ChatBot ──
    aiAssistant: "ኔጋሪት AI ረዳት",
    askAboutCybersecurity: "ስለ ሳይበር ደህንነት ይጠይቁ...",
    sorryCouldNotProcess: "ይቅርታ፣ ያንን ማስኬድ አልቻልኩም።",
    networkErrorChat: "የአውታረ መረብ ስህተት። እባክዎ እንደገና ይሞክሩ።",
    welcomeMessage: "ሰላም! እኔ ኔጋሪት AI ረዳት ነኝ። ስለ ማጭበርበር፣ ሳይበር ደህንነት ወይም ኔጋሪት AI ምን ሊያደርግልዎ እንደሚችል ይጠይቁ።",
    // ── Navbar ──
    navAnalyze: "ተንትን",
    navFeatures: "ባህሪያት",
    navHowItWorks: "እንዴት እንደሚሰራ",
    navFaq: "ተየጥ",
    startFreeTrial: "ነፃ ሙከራ ይጀምሩ",
    toggleMenu: "ምናሌ ይቀይሩ",
    // ── HeroSection ──
    enterpriseGradeProtection: "የኢንተርፕራይዝ ደረጃ ጥበቃ",
    heroHeading: "ከAI ማጭበርበሮች፣ ፊሽንግ እና ዲፕፌክ እራስዎን ይጠብቁ",
    heroDescription: "ኔጋሪት AI አጠራጣሪ መልእክቶችን፣ ዩአርኤሎችን፣ ስክሪን ሾቶችን እና በAI የተፈጠሩ ምስሎችን በመተንተን የሳይበር ስጋቶችን እርስዎ ላይ ከመድረሳቸው በፊት ይለያል።",
    analyzeNow: "አሁን ተንትን",
    learnMore: "ተጨማሪ ይረዱ",
    trustedBy: "የታመነው በ",
    securityProfessionals: "የደህንነት ባለሙያዎች",
    // ── Features ──
    everythingToStaySafe: "ለመጠበቅ የሚያስፈልግዎ ሁሉ",
    sixEnginesWorking: "ከዘመናዊ የሳይበር ስጋቶች ድርጅትዎን ለመጠበቅ አንድ ላይ የሚሰሩ ስድስት ኃይለኛ ሞተሮች።",
    aiMessageAnalysisTitle: "AI የመልእክት ትንተና",
    aiMessageAnalysisDesc: "አጠራጣሪ ኢሜይሎችን እና ኤስኤምኤስን በቅጽበት ይተንትኑ።",
    imageDeepfakeDetectionTitle: "ምስል ዲፕፌክ መለየት",
    imageDeepfakeDetectionDesc: "በAI የተፈጠሩ ፊቶችን እና ሰነዶችን ለማጋለጥ የፒክሰል ደረጃ የጩኸት ቅጦችን ይመርምሩ።",
    urlScannerTitle: "ዩአርኤል ቃኚ",
    urlScannerDesc: "ሊንኮችን በተናጥል ማገጃዎች ውስጥ በጥልቀት ይቃኙ።",
    platformSupportTitle: "የመድረክ ድጋፍ",
    platformSupportDesc: "ለዋትሳፕ፣ ቴሌግራም እና ስላክ በኤፒአይ፣ በአሳሽ ቅጥያዎች እና በቻት ቦቶች በኩል የተፈጥሮ ውህደቶች።",
    realtimeAlertsTitle: "የቅጽበት ማንቂያዎች",
    realtimeAlertsDesc: "ከፍተኛ እምነት ያላቸው ስጋቶች ድርጅትዎን ሲያነጣጥሩ ወዲያውኑ ማሳወቂያዎችን ያግኙ።",
    enterpriseReportsTitle: "የኢንተርፕራይዝ ሪፖርቶች",
    enterpriseReportsDesc: "ለደህንነት ቡድኖች፣ ለተገዢነት ባለስልጣናት ወይም ለህግ አስከባሪ አካላት ዝርዝር የPDF ሪፖርቶችን ያፍሱ።",
    // ── Workflow ──
    securityInThreeSteps: "ደህንነት በሦስት ቀላል ደረጃዎች",
    workflowDesc: "ከማቅረብ እስከ ፍርድ በሰከንዶች ውስጥ — ምንም ስልጠና አያስፈልግም።",
    submitContentStep: "ይዘት ያስገቡ",
    submitContentStepDesc: "ዩአርኤል ይለጥፉ፣ ምስል ይጫኑ፣ ወይም አጠራጣሪ መልእክት ወደ ዳሽቦርድዎ ወይም ኤፒአይ ያስተላልፉ።",
    aiAnalysisStep: "AI ትንተና",
    aiAnalysisStepDesc: "ሞዴሎቻችን ይዘቱን ለቋንቋ ያልተለመዱ ነገሮች፣ የዲፕፌክ ዱካዎች እና ተንኮል-አዘል ኮድ ይመረምራሉ።",
    getResultsStep: "ውጤት ያግኙ",
    getResultsStepDesc: "ወዲያውኑ ፍርድ (አስተማማኝ፣ አጠራጣሪ፣ ወይም አደገኛ) ከዝርዝር ግኝቶች ጋር ይቀበሉ።",
    // ── Testimonials ──
    testimonials: "ምስክርነቶች",
    trustedByTeams: "በደህንነት ቡድኖች የታመነ",
    testimonialsDesc: "በየቀኑ ኔጋሪት AI ከሚጠቀሙ ባለሙያዎች ይስሙ።",
    testimonial1Text: "ኔጋሪት AI የኢሜይል መግቢያችንን ያለፈ ውስብስብ የጦር መሳሪያ ፊሽንግ ዘመቻ ያዘ።",
    testimonial1Author: "ሳራ ድራስነር",
    testimonial1Role: "CISO, ፊንቴክ ግሎባል",
    testimonial2Text: "ለከፍተኛ ሀብት ደንበኞቻችን የዋትሳፕ ቦት አሰማርተናል። አጠራጣሪ የክሪፕቶ ሊንኮችን አስተላልፈው ወዲያውኑ የደህንነት ደረጃ ያገኛሉ።",
    testimonial2Author: "ማርከስ ሪድ",
    testimonial2Role: "የደህንነት VP, ቩልት ዲጂታል",
    testimonial3Text: "የኤፒአይ ውህደቱ እንከን የለሽ ነበር። በAI የተፈጠሩ ሰው ሰራሽ መለያዎችን ለመለየት ሁሉንም የተጠቃሚ የKYC ሰነዶች በኔጋሪት ውስጥ እናስገባለን።",
    testimonial3Author: "ኤሌና ሊን",
    testimonial3Role: "ዋና መሀንዲስ, እምነት እና ደህንነት",
    // ── FAQ Section ──
    faqSectionTitle: "በተደጋጋሚ የሚጠየቁ ጥያቄዎች",
    faqSectionDesc: "ስለ ኔጋሪት AI ማወቅ ያለብዎት ሁሉ።",
    faq1Q: "የዲፕፌክ መለየቱ ምን ያህል ትክክለኛ ነው?",
    faq1A: "ኔጋሪት AI ባለብዙ-ሞዳል ትንተና በመጠቀም 99.4% ትክክለኛነትን ያስመዘግባል።",
    faq2Q: "ለመላው ቡድኔ ልጠቀምበት እችላለሁ?",
    faq2A: "አዎ፣ ኔጋሪት AI ከሚና-ተኮር ተደራሽነት እና ከማዕከላዊ ሪፖርት ጋር የቡድን አቀፍ ማሰማራትን ይደግፋል።",
    faq3Q: "የተተነተነውን ይዘት ታከማሻላችሁ?",
    faq3A: "አይ፣ የተተነተነ ይዘት በደህንነት ይሰራል እና በግልጽ ካልተጠየቀ በስተቀር አይከማችም።",
    faq4Q: "ከዋትሳፕ እና ቴሌግራም ጋር ይሰራል?",
    faq4A: "አዎ፣ ተጠቃሚዎችን በሚሰሩበት ቦታ ለመጠበቅ ለዋትሳፕ እና ቴሌግራም ቤተኛ ቦቶችን እናቀርባለን።",
    faq5Q: "የዩአርኤል ቃኚው ምን ያህል ፈጣን ነው?",
    faq5A: "የኛ የአሸዋ ሳጥን ቃኚ ለተወሳሰበ የማዞሪያ ሰንሰለቶች እንኳን በ2 ሰከንድ ውስጥ ውጤት ያቀርባል።",
    // ── Footer ──
    product: "ምርት",
    resources: "መረጃዎች",
    company: "ኩባንያ",
    documentation: "ሰነዶች",
    apiReference: "የኤፒአይ ማጣቀሻ",
    securityReports: "የደህንነት ሪፖርቶች",
    blog: "ብሎግ",
    aboutUs: "ስለ እኛ",
    careers: "ስራዎች",
    contact: "ያግኙን",
    privacyPolicy: "የግላዊነት ፖሊሲ",
    allSystemsOperational: "ሁሉም ስርዓቶች ይሰራሉ",
    copyrightFooter: "© 2024 ኔጋሪት AI Inc. መብቱ በህግ የተጠበቀ ነው።",
    footerDescription: "ከAI ማጭበርበሮች፣ ፊሽንግ እና ዲፕፌክ የኢንተርፕራይዝ ደረጃ ጥበቃ። የዲጂታል ድንበርን መጠበቅ።",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  useEffect(() => {
    const saved = localStorage.getItem("lang");
    if (saved) setLang(saved);
  }, []);

  useEffect(() => {
    localStorage.setItem("lang", lang);
  }, [lang]);

  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;

  const toggleLang = () => setLang((prev) => (prev === "en" ? "am" : "en"));

  const changeLang = (code) => setLang(code);

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang, changeLang, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
